# Generated by Django 4.2.8 on 2023-12-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_type',
        ),
        migrations.AddField(
            model_name='users',
            name='is_Ops',
            field=models.BooleanField(default='False'),
        ),
    ]
