# Generated by Django 4.2.8 on 2023-12-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_users_user_type_users_is_ops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_Ops',
        ),
        migrations.AddField(
            model_name='users',
            name='user_type',
            field=models.CharField(default='Client', max_length=100),
        ),
    ]
