# Generated by Django 4.2.8 on 2023-12-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_users_is_ops_users_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_type',
        ),
        migrations.AddField(
            model_name='users',
            name='is_ops',
            field=models.BooleanField(default=False),
        ),
    ]
