# Generated by Django 4.2.8 on 2023-12-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_users_user_type_users_is_ops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
